- name: configure postgresql
  hosts: _ansible_postgresql
  become: yes
  vars_files: 
    - ~/secret.yml
  tasks:
    - name: update packages
      yum: 
        name: "*"
        state: latest
    - name: Uninstall old versions
      yum:
        name: "{{ item }}"
        state: removed
      loop:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine    
    - name: install yum-utils
      yum:
        name: yum-utils
        state: latest   
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      package:
        name: docker-ce
        state: latest

    - name: Install pip
      package: 
        name: python3-pip
        state: present
        
    - name: Install docker sdk
      pip:
        name: docker   

    - name: add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: start docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: create build directory
      file:
        path: /home/ec2-user/postgresql
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: copy the sql script
      copy: 
        src: /home/ec2-user/ansible/dependency_files/postgres/init.sql
        dest: /home/ec2-user/postgresql  

    - name: Pull  docker image
      shell: docker pull engingltekin/todo-app-pern-postgres:latest
    
    - name: create postgresql docker container
      docker_container:
        name: engin_postgres
        image: engingltekin/todo-app-pern-postgres:latest
        state: started
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "{{ password }}"
        volumes:
          - /db-data:/var/lib/postgresql/data
      register: container_info

    - name: print the container info
      debug:
        var: container_info     
            