apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  selector:
    app: phonebook-crud
  type: NodePort      
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 3000
      targetPort: 80