apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql-deployment
  labels:
    app:  mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata: 
      labels:
        app: mysql
    spec: 
      containers:
      - name:  mysql
        image:  mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name:  MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mysql-secret
              key: mysql-root-password
        - name:  MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_USER
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: mysql-username
        - name: MYSQL_DATABASE
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: mysql-database  
        volumeMounts:
          - name: mysql-storage
            mountPath: /mnt/data
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim                          
