apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: phonebook-web
  type: NodePort  
  ports:
    - protocol: TCP
      nodePort: 30002
      port: 5000
      targetPort: 80